CakeFactoryProd/Controllers/FillingsController.cs
using CakeFactoryProd.Data;
using CakeFactoryProd.Models;
using CakeFactoryProd.Repositories;
using CakeFactoryProd.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace CakeFactoryProd.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FillingsController : Controller
    {
        private readonly CakeFactoryContext _context;

        public FillingsController(CakeFactoryContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            FillingsRepo fillingsRepo = new FillingsRepo(_context);
            var fillingsList = fillingsRepo.GetAllFillings();
            return View(fillingsList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(FillingVM fillingVM)
        {
               FillingsRepo fillingsRepo= new FillingsRepo(_context);
                var response = fillingsRepo.CreateNewFilling(fillingVM);
                return RedirectToAction("Index"); ;

        }

        public IActionResult Delete(int id)
        {
            FillingsRepo fillingsRepo = new FillingsRepo(_context);
            var filling = fillingsRepo.GetFillingById(id);
            return View(filling);
        }

        [HttpPost]
        public IActionResult Delete(Filling filling)
        {
                FillingsRepo fillingsRepo = new FillingsRepo(_context);
                var response = fillingsRepo.DeleteFillingById(filling.Id);
                return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            FillingsRepo fillingsRepository = new FillingsRepo(_context);
            var filling = fillingsRepository.GetFillingById(id);
            return View(filling);
        }

        public IActionResult Edit(int id)
        {
            FillingsRepo fillingsRepo = new FillingsRepo(_context);
            var filling = fillingsRepo.GetFillingById(id);
            return View(filling);
        }

        [HttpPost]

        public IActionResult Edit(Filling filling)
        {
            FillingsRepo fillingsRepo = new FillingsRepo(_context);
            FillingVM fillingVM = new FillingVM()
            {
                Flavor = filling.Flavor,
                PriceFactor = filling.PriceFactor,
                FillingId = filling.Id,
                Description = filling.Description,
                IsActive = filling.IsActive
            };
            var response = fillingsRepo.UpdateFillingByID(fillingVM);
            return RedirectToAction("Details", new {id = filling.Id});
        }
    }
}

CakeFactoryProd/Views/Fillings/Create.cshtml
@model CakeFactoryProd.ViewModels.FillingVM

@{
    Layout = "~/Views/Shared/Admin/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Filling</h4>
<hr />
<div class="row justify-content-around">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Flavor" class="control-label"></label>
                <input asp-for="Flavor" class="form-control" />
                <span asp-validation-for="Flavor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceFactor" class="control-label"></label>
                <input asp-for="PriceFactor" class="form-control" />
                <span asp-validation-for="PriceFactor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CakeFactoryProd/Views/Fillings/Delete.cshtml
@model CakeFactoryProd.Models.Filling

@{
    Layout = "~/Views/Shared/Admin/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Filling</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flavor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flavor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceFactor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceFactor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CakeFactoryProd/Views/Fillings/Details.cshtml
@model CakeFactoryProd.Models.Filling

@{
    Layout = "~/Views/Shared/Admin/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Filling</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flavor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flavor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceFactor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceFactor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CakeFactoryProd/Views/Fillings/Edit.cshtml
@model CakeFactoryProd.Models.Filling

@{
    Layout = "~/Views/Shared/Admin/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Filling</h4>
<hr />
<div class="row justify-content-around">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Flavor" class="control-label"></label>
                <input asp-for="Flavor" class="form-control" />
                <span asp-validation-for="Flavor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceFactor" class="control-label"></label>
                <input asp-for="PriceFactor" class="form-control" />
                <span asp-validation-for="PriceFactor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CakeFactoryProd/Views/Fillings/Index.cshtml
@model IEnumerable<CakeFactoryProd.Models.Filling>

@{
    Layout = "~/Views/Shared/Admin/_AdminLayout.cshtml";
}
<a asp-action="Cakes" asp-controller="Admin">Cakes</a>|<a asp-action="Index" asp-controller="Toppings">Toppings</a>|<a asp-action="Index" asp-controller="Fillings">Fillings</a>|<a asp-action="Index" asp-controller="Shape">Shapes</a>

<h1>Fillings</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Flavor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceFactor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Flavor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceFactor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                    @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                    @Html.ActionLink("Delete", "Delete", new {id = item.Id})
            </td>
        </tr>
}
    </tbody>
</table>